//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileProperty
    {
        public System.Guid Id { get; set; }
        public System.Guid FileId { get; set; }
        public System.Guid PropertyId { get; set; }
        public string Value { get; set; }
    
        public virtual File File { get; set; }
        public virtual Property Property { get; set; }
    }
}
